version: '3'

services:
  deploy:
    build:
      context: .
    env_file:
      - instance-manager-properties.env
    command: bash -c "sls deploy --verbose --region $${AWS_REGION} --stage $${STAGE}"
