service: ec2-instance-manager

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  environment:
    INSTANCE_IDS: ${env:INSTANCE_IDS}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

    - Effect: Allow
      Action:
        - ec2:Start*
        - ec2:Stop*
      Resource: "*"

functions:
  stop-instances:
    handler: handlers/scheduled.stop_instances
    events:
      - schedule: ${env:STOP_INSTANCE_CRON}

  start-instances:
    handler: handlers/scheduled.start_instances
    events:
      - schedule: ${env:START_INSTANCE_CRON_1}
      - schedule: ${env:START_INSTANCE_CRON_2}

  telegram-message-handler:
    handler: handlers/telegram_bot.handle
    environment:
      TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    events:
      - http:
          path: instance_manager/api/telegram/handle
          method: post
          cors:
            origin: '*'

package:
  patterns:
    - '!node_modules/**'
    - '!package*'
