service: ec2-instance-manager

provider:
  name: aws
  runtime: python3.8
  environment:
    INSTANCE_IDS: ${env:INSTANCE_IDS}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "arn:aws:logs:*:*:*"

    - Effect: Allow
      Action:
        - ec2:Start*
        - ec2:Stop*
      Resource: "*"

functions:
  stopInstances:
    handler: handlers/instance_manager.stop_instances
    events:
      - schedule: ${env:STOP_INSTANCE_CRON}

  startInstances:
    handler: handlers/instance_manager.start_instances
    events:
      - schedule: ${env:START_INSTANCE_CRON_1}
      - schedule: ${env:START_INSTANCE_CRON_2}
